FROM node:12.11-alpine

# create destination directory
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install
COPY .nuxt ./.nuxt

# build necessary, even if no static files are needed,
# since it builds the server as well
# RUN npm run build

# expose 5000 on container
# set app serving to permissive / assigned
ENV NUXT_HOST=0.0.0.0
# set app port
ENV NUXT_PORT=5000

# start the app
CMD [ "npm", "start" ]
